export const cardsData = [
  { id: "1", name: "ACard", value: "low", img: "../assets/cards/a-card.png" },
  { id: "2", name: "JCard", value: "low", img: "../assets/cards/j-card.png" },
  { id: "3", name: "KCard", value: "low", img: "../assets/cards/k-card.png" },
  { id: "4", name: "QCard", value: "low", img: "../assets/cards/q-card.png" },
  {
    id: "5",
    name: "Flamingo",
    value: "medium",
    img: "../assets/cards/flamingo-card.png",
  },
  {
    id: "6",
    name: "Plane",
    value: "medium",
    img: "../assets/cards/plane-card.png",
  },
  {
    id: "7",
    name: "Gun",
    value: "high",
    img: "../assets/cards/gun-card.png",
  },
  {
    id: "8",
    name: "WalkieTalkie",
    value: "high",
    img: "../assets/cards/walkie-talkie-card.png",
  },
  {
    id: "9",
    name: "Jerk",
    value: "high",
    img: "../assets/cards/jerk-card.png",
  },
  {
    id: "10",
    name: "Girl",
    value: "high",
    img: "../assets/cards/girl-card.png",
  },
  {
    id: "11",
    name: "WildCard",
    value: "wild",
    img: "../assets/cards/wild-card.png",
  },
  {
    id: "12",
    name: "WildFire",
    value: "wild",
    img: "../assets/cards/wild-fire.png",
  },
  {
    id: "13",
    name: "FreeSpins",
    value: "free spin",
    img: "../assets/cards/free-spins-card.png",
  },
  {
    id: "14",
    name: "CatchMe",
    value: "catch me",
    img: "../assets/cards/catch-card.png",
  },
];
