export const constants = {
  BASIC_BET: 10,
  START_LEVEL: 1,
  START_COIN_VALUE: 1,
  BASIC_COINS_AMOUNT: 5000,
  SYMBOL_WIDTH: 144,
  SYMBOL_HEIGHT: 196,
  REELS_QUANTITY: 5,
  SYMBOLS_QUANTITY: 3,
}
